# Site settings
title: Robert A. Boria
email: rboria@ucmerced.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a PhD Candidate in the Quatitative Systems Biology graduate group at Univeristy of California- Merced.
  I study how populations have responded to past climate change and how the historical distributions and past areas of climate refugia will influence future climate change responses. 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://robertboria.com" # the base hostname & protocol for your site
twitter_username: rboria00
github_username:  rboria00


# Build settings
markdown: kramdown
theme: minima
